export const androidTasks = [
  {
    year: 1,
    tasks: [
      {
        type: 'quiz-app',
        title: 'Android Quiz App',
        description: [
          '🎯 Task Overview: ',
          'Create an Android Quiz App with multiple screens.',
          '',
          'Screen 1 – User Info Input:',
          'A form that collects the user’s Name and Quiz Level Selection (Easy, Medium, Hard)',
          'A Start Quiz button to begin the quiz.',
          '',
          'Screen 2 – Questions Display:',
          'Display the questions one by one.',
          'Provide radio buttons for answer selection.',
          'Include a Submit button for each question.',
          '',
          'Screen 3 – Score Display:',
          'Display the final score along with the user’s name',
          '',
          '✨ Bonus Features:',
          'Splash Screen with Animation.',
          'Modern UI using Material Design components.',
          'Option to fetch questions from an external API.',
          'A countdown timer for the quiz.',
        ],
        link: '',
        criteria: [
          'Effective UI implementation across all screens',
          'Seamless navigation and data flow between screens',
          'Accurate tracking and display of quiz results',
          'Proper use of Android components and adherence to Material Design principles',
        ],
        browniePoints: [
          'Smooth animation transitions and appealing splash screen',
          'Incorporation of external API to fetch questions',
          'Integration of a functional countdown timer',
        ],
        imageUrl: '',
      },
    ],
  },
  {
    year: 2,
    tasks: [
      {
        type: 'color-memory-game',
        title: 'Color Memory Game App',
        description: [
          '🎯 Task Overview: ',
          'Build a simple Color Memory Game App with three main screens. The app will test the player’s memory by showing a 3x3 grid of colors that the user has to memorize and then reproduce.',
          '',
          'Screen 1 – User Details:',
          'Purpose: To collect the user’s name before the game starts.',
          'Fields: Name (TextField).',
          'Button: “Start Game”.',
          'Validation:	Name should not be empty.',
          'Navigation: On clicking “Start Game”, navigate to Screen 2.',
          '',
          'Screen 2 – Color Grid with Timer:',
          'Display a 3x3 grid filled with 9 randomly generated colors',
          'Show a timer (e.g., 10-second countdown) at the top-right',
          'The user is expected to memorize the colors and their positions',
          'After the timer ends, automatically navigate to Screen 3',
          'Note: The randomly generated grid colors must be saved for later comparison.',
          '',
          'Screen 3 – Color Recall Grid:',
          'Present a blank 3x3 grid (using a neutral color).',
          'On tapping a grid cell, show a dropdown/list dialog with color options to choose from',
          'After user selects all 9 colors, compare the user’s input with the original color grid',
          'If all selections are correct: Show a “You Win, [User Name]!” popup',
          'Else: Show a “You Lose, [User Name]” popup.',
          'Add a “Play Again” button in the result popup to restart from Screen 1',
        ],
        link: '',
        criteria: [
          'Accurate implementation of the three distinct screens',
          'Effective timer functionality and automatic screen transitions',
          'Proper logic for comparing user input with the original color grid',
          'Clean and engaging UI with proper use of Android components',
        ],
        browniePoints: [
          'Integration of RoomDB for storing and displaying game history',
          'Store user game history using RoomDB and display it in the app',
          'Engaging and intuitive UI design.',
          'Overall user engagement and creative UI enhancements',
        ],
        imageUrl: '',
      },
    ],
  },
];

export const mlTasks = [
  {
    year: 1,
    tasks: [
      {
        type: 'Task: Neural Network from Scratch',
        title: 'Task 1: Neural Network from Scratch',
        description: [
          'Objective: ',
          'Implement a basic neural network from scratch to classify simple datasets like XOR or MNIST (digits 0-1 for simplicity).',
          'Tools Allowed: ',
          'PyTorch (without using nn.Module, only use torch.Tensor) OR Pure Python with NumPy',
          'What we expect:',
          'Manual implementation of forward and backward propagation, use of activation functions (ReLU or Sigmoid), a proper training loop with loss computation (MSE or CrossEntropy), and a plot/display of loss reduction over epochs with the final classification accuracy.',
          'Submission: ',
          'Jupyter Notebook (.ipynb) or Python script (.py) including a README explaining your architecture and approach.',
        ],
        link: '',
        criteria: [
          'Correct implementation of forward and backward propagation',
          'Proper use of activation functions',
          'Effective training loop and loss reduction demonstration',
          'Overall classification accuracy and code quality',
        ],
        browniePoints: [
          'Bonus for additional optimization techniques or creative visualization methods',
        ],
        imageUrl: '',
      },
      {
        type: 'Task: DataFrame Manipulation using NumPy + Pandas',
        title: 'Task 2: DataFrame Manipulation using NumPy + Pandas',
        description: [
          'Objective: ',
          'Work with a real-world dataset and perform comprehensive data analysis and manipulation using NumPy and Pandas.',
          'Tools Allowed: Python, Pandas, NumPy, and Matplotlib/Seaborn for visualization',
          'Dataset: Titanic Dataset - https://www.kaggle.com/competitions/titanic/data (clickable link below).',
          'What to Include:',
          'Data Loading and Cleaning: Handle missing values, rename columns, and format data types',
          'DataFrame Operations: Filtering, grouping, sorting, and merging along with statistical summaries and aggregations',
          'NumPy Usage: Vectorized operations and matrix manipulations as needed with basic descriptive stats',
          'Visualization & Insights: At least 2–3 graphs using matplotlib or seaborn, highlighting 3–5 interesting insights',
          '(Bonus) Model Training & Evaluation: Optionally train a classification model and explain your results',
          'Submission:',
          'Jupyter Notebook (.ipynb) or Python script (.py) along with a README describing your approach.',
        ],
        link: 'https://www.kaggle.com/competitions/titanic/data',
        criteria: [
          'Data cleaning and manipulation effectiveness',
          'Quality and depth of exploratory data analysis',
          'Insightfulness and clarity of visualizations',
          'Overall code quality and readability',
        ],
        browniePoints: [
          'Bonus for integrating a classification model with detailed evaluation and clear explanations',
        ],
        imageUrl: '',
      },
    ],
  },
  {
    year: 2,
    tasks: [
      {
        type: 'Task: Retrieval-Augmented Generation (RAG) Task',
        title: 'Task 1: Retrieval-Augmented Generation (RAG) Task',
        description: [
          'Objective:',
          'Implement a basic prototype of Retrieval-Augmented Generation (RAG) where a user query retrieves relevant context from documents and generates an answer using a language model.',
          'Tools Allowed:',
          'Langchain, transformers, faiss, or any other retrieval + generation framework. (Optional: Streamlit or Flask for frontend)',
          'What to Include:',
          'Document ingestion and indexing.',
          'Query-based retrieval (e.g., using FAISS or a vector store)',
          'Context-aware generation of answers using a model like GPT-2, T5, etc.',
          'Include sample queries and corresponding responses',
          'Submission: ',
          'GitHub repository or ZIP file containing your code along with a README.',
        ],
        link: '',
        criteria: [
          'System functionality and stability',
          'Efficiency of document processing and indexing',
          'Accuracy and relevance of generated responses',
          'Integration and optional API/frontend implementation (if applicable)',
        ],
        browniePoints: [
          'Extra credit for LangChain integration',
          'Performance optimization improvements',
          'Advanced query handling',
        ],
        imageUrl: '',
      },
      {
        type: 'Task: News Sentiment Analysis Pipeline',
        title: 'Task 2: News Sentiment Analysis Pipeline',
        description: [
          'Objective: ',
          'Build a sentiment analysis model that classifies news headlines or content into Positive, Negative, or Neutral sentiment categories.',
          'Dataset: News Sentiment Analysis Dataset – available on Kaggle',
          'Tools Allowed: ',
          'Machine Learning libraries (Scikit-learn, TensorFlow, or PyTorch), text preprocessing tools (NLTK, spaCy, Regex), and optionally HuggingFace Transformers for advanced models (BERT, LSTM-based approaches)',
          'What to Include:',
          'Data Preprocessing: Load and clean the dataset, handle missing values, perform tokenization, stopword removal, and lemmatization/stemming, and apply label encoding',
          'Model Building: Develop models for sentiment classification using either classical methods (e.g., Logistic Regression, Naive Bayes, SVM) or deep learning approaches (e.g., LSTM, BERT)',
          'Evaluation: Use metrics like Accuracy, Precision, Recall, F1 Score and include a confusion matrix along with accuracy/loss graphs as applicable',
          'Submission:',
          'Jupyter Notebook (.ipynb) or GitHub repository including a README that explains your dataset summary, preprocessing steps, models used, evaluation results, and any challenges encountered.',
        ],
        link: 'https://www.kaggle.com/datasets/myrios/news-sentiment-analysis',
        criteria: [
          'Quality of data preprocessing and cleaning',
          'Model accuracy and reliability',
          'Effectiveness of evaluation metrics and visualizations',
          'Overall code quality and clarity',
        ],
        browniePoints: [
          'Bonus for incorporating advanced NLP techniques',
          'Real-time processing enhancements',
          'Deployment readiness of the demo',
          'Visualize the most common words in each sentiment class and deploy a simple demo using Streamlit or Flask',
        ],
        imageUrl: '',
      },
    ],
  },
];

export const designTasks = [
  {
    year: 1,
    gfx: [
      {
        description: [
          'Logo for a company',
          'Design a logo for any toy making company. Think of a fun, playful, and colorful design style. Come up with a creative name for the toy company.',
          'Social Media Post',
          'Design social media posts for recruitments of GDG-on campus jssaten where you must cover basic information like the clubs, timeline and processes and perks of joining GDG.',
        ],
        link: '',
        criteria: ['Relevance to industry', 'Typography quality', 'Color scheme'],
        browniePoints: ['Vector format', 'Multiple variations'],
      },
    ],
    ux: [
      {
        description: [
          'Redesign 99acres',
          'Deliverables : Wireframes, Prototype and visual designs are must.',
          'Conducting user research is a plus.',
          'Redesign Swiggy',
          'Deliverables : Wireframes, Prototype and visual designs are must.',
          'Conducting user research is a plus.',
          'Redesign Snapchat',
          'Deliverables : Wireframes, Prototype and visual designs are must.',
          'Conducting user research is a plus.',
        ],
        link: '',
        criteria: ['User flow improvements', 'Accessibility'],
        browniePoints: ['Design system implementation'],
      },
    ],
    // vfx: [
    //   // {
    //   //   description: [
    //   //     'Create a basic text and confetti animation using any video animation software.',
    //   //     'Create a music video that features dynamic and fast-paced typography animations that are synchronised with the tempo and beat of the music.',
    //   //   ],
    //   //   link: 'https://www.youtube.com/watch?v=8ZtV6c4qY9o',
    //   //   criteria: ['Smooth animation', 'Creative execution'],
    //   //   browniePoints: ['Complex transitions'],
    //   // },
    // ],
  },
  {
    year: 2,
    gfx: [
      {
        description: [
          'Social Media Post',
          'Create a visually stunning poster for any movie.',
          'Challenge : Make it as cinematic as possible. Bring the movie’s mood, story, and vibe to life through your poster using visuals, colors, typography,',
        ],
        link: '',
        criteria: [
          'Clarity of networking theme',
          'Scalability across surfaces',
          'Brand adaptability',
          'Rebrand consistency',
        ],
        browniePoints: [
          'Multi-format export capabilities',
          'Comprehensive brand guidelines',
          'Packaging mockups',
          'Monochrome variations',
        ],
        imageUrl: '',
      },
    ],
    ux: [
      {
        description: [
          'Redesign & fix 2+ UX issues on YONO SBI homepage',
          'You are required to completely redesign the home page of the YONO SBI app, focusing on improving the user experience by identifying and solving at least two UX flaws.',
          'Deliverables: Include User research, competitive analysis, wireframes, Prototype, visual designs and design style guide, brief explanation for:',
          'What UX flaws you found.',
          'How your redesign solves them.',
        ],
        link: '',
        criteria: [
          'User flow optimization',
          'Accessibility compliance',
          'Visual hierarchy',
          'Platform consistency',
        ],
        browniePoints: [
          'Micro-interaction design',
          'Dark mode implementation',
          'User testing results',
          'Design system documentation',
        ],
        imageUrl: '/design-task.png',
      },
    ],
    // vfx: [
    //   {
    //     description: [
    //       '3D Logo Animation',
    //       'Create a 3D animated logo for a music streaming service that works as both a static favicon (256x256) and animated loading screen (1080p). Ensure smooth transitions between states.',
    //       'CGI Integration',
    //       'Enhance stock footage (from Pexels) by adding animated CGI characters to pastoral scene. Maintain realistic lighting and shadows while adding fantastic elements.',
    //     ],
    //     link: 'https://www.pexels.com',
    //     criteria: [
    //       'Technical precision (favicon scaling)',
    //       'Animation smoothness',
    //       'Lighting consistency',
    //       'Asset optimization',
    //     ],
    //     browniePoints: [
    //       'Seamless loop animation',
    //       'Dynamic LOD adjustments',
    //       'Particle effects',
    //       'Sound-sync for music logo',
    //     ],
    //     imageUrl: '/task-example.png',
    //   },
    // ],
  },
];

export const webDevTasks = [
  {
    year: 1,
    tasks: [
      {
        title: 'Movie Explorer (TMDB - The Movie Database)',
        description: [
          'Recreate the UI and interactivity of the reference movie exploration website by observing its design.',
          'The layout should include a navigation bar, search bar, movie listing/grid section, and a movie details popup or page.',
          'Try to maintain a clean layout with a focus on visual appeal, readability, and responsiveness. Present essential movie information like title, poster, rating, release year, and genre.',
          'You can use dummy data (static JSON) or mock movie objects to simulate functionality (actual API integration not required).',
        ],
        link: 'https://www.themoviedb.org/',
        criteria: [
          'HTML, CSS, and JavaScript',
          'Modern frontend framework like React.js or Vue.js. (optional)',
          'UI framework like Tailwind CSS, Bootstrap, or Material UI (optional)',
        ],
        browniePoints: [
          'Host the project on GitHub Pages, Netlify, or Vercel, and provide a live demo link.',
          'Add interactive features like hover effects, modals for movie previews, or dark mode toggle.',
          'Include smooth scroll animations using libraries like Animate.css or Framer Motion.',
          'Include a README file with screenshots, project structure, and setup instructions',
        ],
        imageUrl: '/tmdb.png',
      },
      {
        title: ' Digital Bookshelf / Book Library API',
        description: [
          'Implement a simple CRUD (Create, Read, Update, Delete) operation for books. Each book should include fields like title, author, ISBN, genre, and availability (e.g., available/borrowed).',
          'Use either a database (e.g., MongoDB) or a JSON file to persistently store book data.',
          'Test your APIs using Postman to ensure functionality and reliability.',
          'Choose a reliable framework for backend development (e.g., Express.js for Node.js, Django for Python).',
          'If you don’t want to use a database, then create a JSON file for implementing all the functionalities mentioned above.',
        ],
        link: '',
        criteria: [
          'Language: JavaScript',
          'Runtime: Node.js',
          'Framework: Express',
          'Storage: JSON file (using fs module) or SQL/NoSQL database',
        ],
        browniePoints: [
          'Try to write clean code and have proper comments.',
          'Split the code into folders (like controllers, routers, etc.) to keep the code modular.',
          'Use appropriate variable names, don’t use general names..',
        ],
      },
    ],
  },
  {
    year: 2,
    tasks: [
      {
        title: 'Resume Enhancement Platform',
        description: [
          'Problem',
          'Job seekers often struggle to keep up with evolving job descriptions and tailor their resumes effectively.',
          'Project Overview',
          'Creating a that uses Generative AI to help job seekers tailor their resumes to specific job descriptions. By uploading a resume and job post, the system rewrites and aligns content using prompt engineering, boosting ATS compatibility and recruiter appeal.',
          'Core features:',
          '- User Uploads Resume (PDF)',
          'Resume is parsed and converted to text using OCR/NLP.',
          '- Job Description Input: ',
          'Either pasted as text or uploaded.',
          '-AI Matching Engine (Gemini): ',
          'Analyzes the job description for required skills, experiences, tools, and keywords.',
          'Compares with the resume.',
          'Suggests edits and rewrites content to better align with the job using Gemini or any other LLM model.',
        ],
        criteria: [
          'Backend: Node.js / Python',
          'AI/LLM: Google Gemini API or any other',
          'PDF Parsing: pick any library (eg pdf-parse for node.js)',
          'Frontend: React.js / Next.js / Vue.js or any framework of your choice.',
          ,
          'Storage: AWS S3 / Firebase for file handling (adding storage to the project is optional)',
          'DB: PostgreSQL / MongoDB (adding database to the project is optional)',
          'Auth: no authentication required',
        ],
        browniePoints: [
          'Match Score: Showing users a percentage-based similarity score between the resume and job description.',
          'Cover Letter Generator: Tailored cover letter based on the job + resume using LLMs.',
          'Skill Gap Analyzer: Telling users what skills/certifications to acquire to fit the role.',
          'ATS Simulation: Showing which parts of the resume are likely to be flagged or ignored by ATS.',
        ],
        link: '',
        imageUrl: '',
      },
      {
        title: 'Mood Tracking Application',
        description: [
          'Problem: ',
          'In todays fast-paced world, people often neglect their emotional well-being due to busy schedules and a lack of self-reflection. Without consistent mood tracking, it becomes difficult to identify emotional patterns, stress triggers, or mental health trends that could lead to burnout, anxiety, or depression.',
          'Project Overview: ',
          'Create a beautifully designed mood tracking web app that allows users to log their mood daily using an intuitive built-in calendar UI. The platform helps users visualize emotional trends over time, reflect on their mental health, and gain insights through simple journaling and color-coded emotion mapping.',
          'Core Feaures: ',
          '- Build in interactive Calendar UI',
          'Monthly view with clickable days.',
          'Color-coded mood entries (e.g., happy = yellow, anxious = red).',
          '- Daily Mood Logging',
          'Select mood from a set of emojis or tags (Happy, Sad, Angry, Anxious, Calm).',
          'Optional short journal entry (max 140 characters).',
          '- User Authentication is required',
          'JWT or Auth.',
        ],
        browniePoints: [
          'Mood Visualization',
          'Graphs for weekly/monthly mood trends',
          'Highlight emotional highs/lows',
          'Editable Entries',
          'Click any past day to update mood or journal',
          'Light/Dark Mode Toggle',
        ],
        criteria: [
          'Backend: Node.js / Python',
          'DB: PostgreSQL / MongoDB (Supabase, Firebase)',
          'Auth: Pick any library you’re comfortable with',
          'Frontend: React.js / Next.js / Vue.js or any framework of your choice.',
          'Styling: Tailwind CSS / ShadCN or any other library',
          'Calender UI: Do your own research',
          'Charts library: Do your own research (optional feature)',
        ],
        link: '',
        imageUrl: '',
      },
      {
        title: 'Secure Document Vault Rest API',
        description: [
          'Problem: ',
          'Small teams often need a basic, secure way to upload and share files (like PDFs) with access control — so only the right people can view or manage documents',
          'Project Overview: ',
          'Create a backend API that allows users to upload, view, and manage documents, while enforcing role-based access control (Admin, Editor, Viewer). Admins can assign roles to users, and access to documents is restricted based on those roles.',
          'Core Features: ',
          '1: User Authentication',
          'Basic registration & login with JWT.',
          '2: Roles: Admin, Editor, Viewer',
          'Admin: Full control (upload, manage users, delete files).',
          'Editor: Upload and view.',
          'Viewer: View/download only.',
          '3: File Upload & Download',
          'Users can upload PDFs.',
          'Uploaded files are stored with metadata (filename, uploader, timestamp).',
          'Only authorized users can access the document.',
          '4: Access Control Middleware',
        ],
        browniePoints: [
          'Basic Audit Log - Log when users upload or download a document',
          'Admin can assign/reassign roles to users',
          'File metadata history (e.g., when it was last accessed)',
        ],
        criteria: [
          'Backend: Node.js + Express / Python + FastAPI',
          'DB: PostgreSQL / MongoDB (Supabase, Firebase)',
          'Auth: JWT + Bcrypt',
          'File upload: Multer + local storage (or Cloudinary/S3 if you want)',
          'Proper API documentation is required as readme.md file.',
        ],
        link: '',
        imageUrl: '',
      },
    ],
  },
];
